- hosts: debian
  become: true
  name: Update debian-based vm,lxc
  tasks:
    - name: Upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Check that the reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: r
    - name: Reboot if needed
      reboot:
        msg: "Machine will be rebooted"
      when: r.stat.exists
    - name: Autoremove
      apt:
        autoremove: yes
