services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /smb/media/docker/config/arrs/sonarr:/config
      - /smb/media/series:/series #optional
      - /smb/media/downloads/torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /smb/media/docker/config/arrs/radarr:/config
      - /smb/media/movies:/movies #optional
      - /smb/media/downloads/torrents:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /smb/media/docker/config/arrs/bazarr:/config
      - /smb/media/movies:/movies #optional
      - /smb/media/series:/series #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /smb/media/downloads/metube:/downloads
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /smb/media/docker/config/arrs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped      
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=$TZ
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped    
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=$TZ
       ports:
            - 5055:5055
       volumes:
            - /smb/media/docker/config/arrs/jellyseer:/app/config
       restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /smb/media/docker/config/arrs/lidarr:/config
      - /smb/media/music:/music #optional
      - /smb/media/downloads/torrents:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /smb/media/docker/config/arrs/readarr:/config
      - /smb/media/books:/books #optional
      - /smb/media/downloads/torrents:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PGID
      - PGID=$PUID
      - TZ=$TZ
      - WEBUI_PORT=8080
    volumes:
      - /smb/media/docker/config/arrs/qbitt:/config
      - /smb/media/downloads/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped    
