version: '3.8'
services:
  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /smb/media/docker/config/networking/nginx/data:/data
      - /smb/media/docker/config/networking/nginx/letsencrypt:/etc/letsencrypt
