# Testing compose file, when testing new docker containers

services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /config/testing/beets:/config
      - /nas/media/music:/music
    ports:
      - 8337:8337
    restart: unless-stopped
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /config/testing/odoo/db:/var/lib/postgresql/data
  odoo:
    image: odoo:latest
    links:
      - db:db
    depends_on:
      - "db"
    ports:
      - 8069:8069
    volumes:
      - /config/testing/odoo/:/etc/odoo