# Testing compose file, when testing new docker containers

services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /config/testing/beets:/config
      - /nas/media/music:/music
    ports:
      - 8337:8337
    restart: unless-stopped
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 67:67/udp
      - 69:69/udp
    volumes:
      - /config/testing/iventoy/iso:/app/iso
      - /config/testing/iventoy/data:/app/data
      - /config/testing/iventoy/log:/app/log
    environment:
      - AUTO_START_PXE=true # optional, true by default
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
    volumes:
      - /config/testing/netbootxyz/config:/config
      - /config/testing/netbootxyz/assets:/assets #optional
    ports:
      - 3001:3001
      - 69:69/udp
      - 8081:80 #optional
    restart: unless-stopped