# Testing compose file, when testing new docker containers

services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /config/testing/beets:/config
      - /nas/media/music:/music
    ports:
      - 8337:8337
    restart: unless-stopped
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 67:67/udp
      - 69:69/udp
    volumes:
      - /config/testing/iventoy/iso:/app/iso
      - /config/testing/iventoy/data:/app/data
      - /config/testing/iventoy/log:/app/log
    environment:
      - AUTO_START_PXE=true # optional, true by default